services:
  postgres:
    image: postgres:latest
    container_name: postgres_iceberg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ~H?z4H`C1314
      POSTGRES_DB: iceberg-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5